### ISSUE TITLE
Уменьшить интервал нотификации

### ISSUE THREAD

**Issue by anry-das** [kkarelinn/APP_K#1]
Сейчас интервал составляет 60 сек. Предлагаю уменьшить до 30 сек, чтобы увеличить точность срабатывания.

**Comment by kkarelinn** [comment]
Commit ae59821
Уменьшить интервал нотификации #1 до 30 сек

**Comment by kkarelinn** [comment]
Commit ae59821
Уменьшить интервал нотификации #1 до 30 сек
